### ISSUE TITLE
DeepCloneTo() creates new objects for target properties

### ISSUE THREAD

**Issue by sokolovsa** [force-net/DeepCloner#11]
Example: 
```
class C1 { public int Prop {get; set;} }
class C2 { public C1 Prop {get; set;} }

var target = new C2 { Prop = new C1() }
var source = new C2 { Prop = new C1() }

var targetC1Before = target.Prop;
source.DeepCloneTo(target);
var targetC1After = target.Prop;

Debug.Assert(object.ReferenceEquals(targetC1Before, targetC1After); // FAIL
```

**Comment by force-net** [comment]
As designed.
`DeepCloneTo` usually for specific usage, e.g. when you need to keep target object itself, without creating new, or, when you need to copy fields from base class to derived.
So, it does not keep existing values of properties of target object (There are no ability to know, what fields should be preserved).

**Comment by sokolovsa** [comment]
ok, thanks for explanation.
