### ISSUE TITLE
Request for info (country of origin)

### ISSUE THREAD

**Issue by Karbinski** [force-net/DeepCloner#16]
Hello:

Would you share the country of origin?

Please and thank-you,

Chad
.

**Comment by niemyjski** [comment]
Hello,

I don't know your answer but I'm curious on why this matters... Just look at and review the source, there is nothing hidden here.

**Comment by Karbinski** [comment]
It matters for compliance with global trade restrictions. Another matter is the presence of encryption technology - that one is answered by looking at the code. It's really just a paper-work thing.

**Comment by force-net** [comment]
I do not think, that my country of origin has any sense for this library and MIT license.
Also, there is no encryption.

**Comment by Karbinski** [comment]
It's not your country of origin, it's where the final build took place (release 0.10.2 that was pushed to nuget.org). I know it hardly seems to matter, given I could download the code and build it myself anywhere on the globe. Like I said, it's really just a paper-work thing.
Regardless if you comment further, thank-you for DeepCloner!
