### ISSUE TITLE
Support for cloning child to parent type

### ISSUE THREAD

**Issue by otryshko** [force-net/DeepCloner#19]
public class Parent{};
public class Child : Parent {};
var parent = new Parent();
var child = new Child();
child.DeepCloneTo(parent); // fails to compile

**Expected behavior**: copy child properties which are present in/inherited from the parent to the parent instance and ignore child's own properties.

**Comment by force-net** [comment]
It's forbidden intentionally because it copies private fields and can break object state. E.g. some artificial example
```
public class Parent {
    protected int state = 1;
    public virtual string GetState() {
        if (state == 1) return "Normal State";
        throw new NotImplementedException("Invalid state");
    }
}

public class Child {
    public Child() {
        state = 2;
    }
    public override string GetState() {
        if(state == 2) return "Normal Child state";
        return base.GetState();
    }
}
```

There are no problem in most cases to return `(Parent)child` object. But in complex states it can break code.

**Comment by otryshko** [comment]
Got it, thank you!
