### ISSUE TITLE
CLR exception with exit code 0x80131506

### ISSUE THREAD

**Issue by snekbaev** [force-net/DeepCloner#3]
Hi,

at the moment I'm investigating why my tests are unstable, i.e. unexpected aborts. Switched from mstest/vstests to nunit, but issue remained. Decided to run them in a smaller chunks, interesting enough that sometimes 50 tests could pass 4-5 runs and fail on 6th, but sometimes fail on every run or on every other run. Moreover, almost always it was a different test running when "abort" has happened. And by abort I mean (and according to event log) - an execution engine exception happening in the clr runtime:
```
The process was terminated due to an internal error in the .NET Runtime at IP 00007FF9C27D92E0 (00007FF9C2220000) with exit code 80131506.
```
Interesting enough another set of tests was always working as expected. Further and still a preliminary investigation indicated that failing tests (some of them) have DeepCloner in use. As the next step I ran nunit-console along with "Debug Diagnostic Tool" and with a single test that used DeepCloner. Then checked the logs, probably the most important findings are:

```
DetailID = 4
	Count:    1
	Type:     System.BadImageFormatException
	Message:  An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
	Stack:    
		[InlinedCallFrame]
		[InlinedCallFrame]
		DomainNeutralILStubClass.IL_STUB_PInvoke(System.Reflection.RuntimeModule, Int32, IntPtr*, Int32, IntPtr*, Int32)
		System.ModuleHandle.ResolveMethodHandleInternalCore(System.Reflection.RuntimeModule, Int32, IntPtr[], Int32, IntPtr[], Int32)
		System.ModuleHandle.ResolveMethodHandleInternal(System.Reflection.RuntimeModule, Int32, System.RuntimeTypeHandle[], System.RuntimeTypeHandle[])
		System.Reflection.RuntimeModule.ResolveMethod(Int32, System.Type[], System.Type[])
		Force.DeepCloner.Helpers.DeepClonerMsilHelper.IsConstructorDoNothing(System.Type, System.Reflection.ConstructorInfo)
		Force.DeepCloner.Helpers.DeepClonerMsilGenerator.GenerateProcessMethod(System.Reflection.Emit.ILGenerator, System.Type, Boolean)
		Force.DeepCloner.Helpers.DeepClonerMsilGenerator.GenerateClonerInternal(System.Type, Boolean)
		Force.DeepCloner.Helpers.DeepClonerCache.GetOrAddClass[[System.__Canon, mscorlib]](System.Type, System.Func`2<System.Type,System.__Canon>)
		Force.DeepCloner.Helpers.DeepClonerGenerator.CloneClassInternal(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_Dictionary`2_82(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_ValidationFailure_81(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_ValidationFailure[]_80(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_List`1_79(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservation_5(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservation[]_4(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_List`1_3(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservationsCollection_2(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_Inventory_1(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		Force.DeepCloner.Helpers.DeepClonerGenerator.CloneObject[[System.__Canon, mscorlib]](System.__Canon)
		REDACTED+<TEST_IN_QUESTION>d__27.MoveNext()
--- rest is redacted
```

and the following:

```
DetailID = 5
	Count:    1
	Type:     System.ArgumentException
	Message:  A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
		Type:     System.BadImageFormatException
		Message:  An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
	Stack:    
		[HelperMethodFrame]
		System.Reflection.RuntimeModule.ResolveMethod(Int32, System.Type[], System.Type[])
		[InlinedCallFrame]
		[InlinedCallFrame]
		DomainNeutralILStubClass.IL_STUB_PInvoke(System.Reflection.RuntimeModule, Int32, IntPtr*, Int32, IntPtr*, Int32)
		System.ModuleHandle.ResolveMethodHandleInternalCore(System.Reflection.RuntimeModule, Int32, IntPtr[], Int32, IntPtr[], Int32)
		System.ModuleHandle.ResolveMethodHandleInternal(System.Reflection.RuntimeModule, Int32, System.RuntimeTypeHandle[], System.RuntimeTypeHandle[])
		System.Reflection.RuntimeModule.ResolveMethod(Int32, System.Type[], System.Type[])
		Force.DeepCloner.Helpers.DeepClonerMsilHelper.IsConstructorDoNothing(System.Type, System.Reflection.ConstructorInfo)
		Force.DeepCloner.Helpers.DeepClonerMsilGenerator.GenerateProcessMethod(System.Reflection.Emit.ILGenerator, System.Type, Boolean)
		Force.DeepCloner.Helpers.DeepClonerMsilGenerator.GenerateClonerInternal(System.Type, Boolean)
		Force.DeepCloner.Helpers.DeepClonerCache.GetOrAddClass[[System.__Canon, mscorlib]](System.Type, System.Func`2<System.Type,System.__Canon>)
		Force.DeepCloner.Helpers.DeepClonerGenerator.CloneClassInternal(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_Dictionary`2_82(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_ValidationFailure_81(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_ValidationFailure[]_80(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_List`1_79(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservation_5(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservation[]_4(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_List`1_3(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_RequiredInventoryReservationsCollection_2(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		DynamicClass.DeepObjectCloner_Inventory_1(System.Object, Force.DeepCloner.Helpers.DeepCloneState)
		Force.DeepCloner.Helpers.DeepClonerGenerator.CloneObject[[System.__Canon, mscorlib]](System.__Canon)
		REDACTED+<TEST_IN_QUESTION>d__27.MoveNext()
--- rest is redacted
```

To verify the assumption I replaced DeepCloner with CloneExtensions for that test:
```
 var inventoryCopy = helper.Inventory.GetClone();//.DeepClone();
```

ran that particular test several times and it seems to be working as expected now.
As mentioned earlier, these are preliminary findings, yet they indicate(?) that DeepCloner generates a malformed IL that crashes the entire runtime. Next, I will migrate to CloneExtensions and run the entire test suite to confirm the assumption. Let's see...

Thank you!

**Comment by snekbaev** [comment]
heh, apparently DeepCloner is able to handle much more - something one doesn't get to appreciate that easily unless compared to alternatives :) Migration will take more time

**Comment by force-net** [comment]
Oh! This is strange problem. I've been aware of it, but I was unable to reproduce it on different environments.
There is some checking code which tries to identify constructor body. And it seems, for some classes or for some .NET Environments it causes such fatal error.

I'll spend more time to locate this issue, but it will be fine, if you locate your class which causes such error.

Anyway, you can try next code to switch to expression mode (slightly slower), it should not cause such errors:
```
typeof(ShallowObjectCloner).GetMethod("SwitchTo", BindingFlags.NonPublic | BindingFlags.Static)
	.Invoke(null, new object[] { true });
```

**Comment by snekbaev** [comment]
~~Switching to the expression mode causes `Process is terminated due to StackOverflowException.`~~. Now in the logs I don't see the aforementioned exceptions, yet runtime crashed with the same exit code `0x80131506`

**Comment by snekbaev** [comment]
One of the reasons why it fails (but not always) is when a base class calls a virtual method. Test case:
[UnitTest1.cs.txt](https://github.com/force-net/DeepCloner/files/1545129/UnitTest1.cs.txt)

Yes, doing that is considered to be a bad practice. I've already refactored and the test seems to pass, however, I'm still crashing under different conditions. Will try to find the next root cause. Meanwhile, if possible, you can add the check to the cloning method if such code is detected or at least mention in the notes.

**Comment by snekbaev** [comment]
By looking further it seems that aforementioned case wasn't the root cause and probably not an issue per se regarding the clr exception, except for the bad coding practice. Now I suspect that runtime crashes due to DeepCloner failing to clone the ```IValidator``` variable. Please see 
[UnitTest2.cs.txt](https://github.com/force-net/DeepCloner/files/1545195/UnitTest2.cs.txt)

I hope we can find a solution soon, I really don't want to expand those one line cloning statements into hundreds of lines, uuuhhh :)

**Comment by force-net** [comment]
Thank you for repory. I've reproduced issue and trying to find it source to fix it.

**Comment by snekbaev** [comment]
Alright, thank you. I'll be waiting :)

**Comment by force-net** [comment]
It seems, I've found an issue. DeepCloner is so **deep**. As a result, it tries to copy _System.Reflection.Emit_ classes up to _InternalAssemblyBuilder_ and this class (or something other) causes rutime to fail.
I forbade to deep copy such classed and exception has gone. 
Tomorrow, I'll additionally check code and will prepare a new release.

**Comment by snekbaev** [comment]
That's awesome! Спасибо!

**Comment by snekbaev** [comment]
... :wink:

**Comment by force-net** [comment]
Sorry for delay, I have no time to publish build previously.
Now, new package is on nuget

**Comment by snekbaev** [comment]
Thank you!
