### ISSUE TITLE
Add DBNull.Value to Force.DeepCloner.Helpers.DeepClonerSafeTypes.KnownTypes

### ISSUE THREAD

**Issue by i2van** [force-net/DeepCloner#6]
## Preface ##
`DBNull.Value` represents ADO.NET `NULL` value and defined as:

```csharp
public static readonly DBNull Value = new DBNull();
```

## Problem ##

Code:

```csharp
if(dataRow["col1"] != DBNull.Value && dataRow["col2"] == DBNull.Value) // ...
```

Let's assume both columns contain `DBNull.Value`. When `dataRow` is cloned by DeepCloner copy of `DBNull.Value` is created for both columns. After cloning first comparison is still `true`, second one changed result to `false` from `true` cause clone of `DBNull` is not `DBNull.Value`.

.NET FW has a lot of `DBNull.Value` comparisons itself which leads to a very strange effects, e.g. changing `DBNull` string in `DataColumn` from `null` to empty string.

## Fix ##

Add `DBNull` to `Force.DeepCloner.Helpers.DeepClonerSafeTypes.KnownTypes`

## Workaround ##

```csharp
// Excluding DBNull from list of cloned types. DeepCloner creates DBNull.Value copy which is static readonly instance of DBNull itself which breaks DBNull.Value reference equality.
var assembly = Assembly.GetAssembly(typeof(DeepClonerExtensions));
var deepClonerSafeTypes = assembly.GetType("Force.DeepCloner.Helpers.DeepClonerSafeTypes");
var knownTypesField = deepClonerSafeTypes.GetField("KnownTypes", BindingFlags.Static | BindingFlags.NonPublic);
var knownTypes = (ConcurrentDictionary<Type, bool>)knownTypesField.GetValue(null);
knownTypes.TryAdd(typeof(DBNull), true);
```

**Comment by force-net** [comment]
Approved. Will be implemented.
