### ISSUE TITLE
Can we have a attribute to ignore some field/property?

### ISSUE THREAD

**Issue by sd016808** [force-net/DeepCloner#7]
I have a class which implemented INotifyPropertyChanged interface.

How can I use deepClone without some property( PropertyChanged event )?

I have tried [field: NonSerialized] and [JsonIgnore], but it still clone the PropertyChanged event.

**Comment by force-net** [comment]
Currently it does not supported by idea of library: "Cloned objects should be same as original and it should not know, that it cloned". 
May be, in future, I'll add support of attributes, but it hard due current optimizations which can clone object with it fields in one step.

**Comment by sd016808** [comment]
I am looking forward to this feature implementation!

I use the MVVM pattern, and most of my classes have implemented INotifyPropertyChanged interface.

If I use deepClone with event/delegate, I will got some memory error and crash problem.

**Comment by Rsverma** [comment]
Having the same issue. Trying to clone an item from grid results in cloning the entire grid internally due to this PropertyChanged Binding.

**Comment by force-net** [comment]
Ok. I'll think, how to better implement such functionality (add some helper function to exclude/override cloning, or attribute, or something else, or all variants).

**Comment by Rsverma** [comment]
It seems an attribute would be the best way to go(if possible) such as the NonSerializedAttribute which prohibits serialization of a field.

**Comment by StevenTCramer** [comment]
Given I don't see a merge or documentation on how to do this.  Should this be reopened?

**Comment by GF-Huang** [comment]
Any progress?
